# Generated by Django 4.0.3 on 2023-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('admission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('treating_doctor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Admissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('bed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField()),
                ('bed_number', models.IntegerField()),
                ('availability', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Beds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('head_of_department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('medication_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('nurse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Nurses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('medication_id', models.IntegerField()),
                ('dosage_instructions', models.CharField(max_length=255)),
                ('date_prescribed', models.DateField()),
            ],
            options={
                'db_table': 'Prescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('surgery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('surgeon_id', models.IntegerField()),
                ('surgery_date', models.DateField()),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Surgeries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Tests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('ward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Wards',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'managed': False},
        ),
    ]
