# Generated by Django 4.0.3 on 2023-11-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_admissions_appointments_beds_departments_doctors_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insurance',
            table='Insurance',
        ),
        migrations.AlterModelTable(
            name='medicalhistory',
            table='MedicalHistory',
        ),
    ]
