# Generated by Django 4.0.3 on 2023-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_insurance_table_alter_medicalhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('nurse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Nurses',
        ),
    ]
