# Generated by Django 4.0.3 on 2023-11-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctorrotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorrotation',
            options={'managed': False},
        ),
    ]
