# Generated by Django 4.0.3 on 2023-11-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctorrotation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorrotation',
            table='doctor_rotation',
        ),
    ]
